Group16 to xyzOrthographicProjection
CIS3250-F21/CIS3250-ClassProject pull request #20
Opened 2021-11-13 04:33 UTC by KyrenePineda

Tests are not great. I will address any problems tomorrow as soon as I can.

2021-11-13 14:16 UTC, andrewlinington requested changes
fix folder issue, update the makefile, and please run your code using make then ./main with valgrind as found in the readme as that will speed up the process for approval

2021-11-13 14:16 UTC, andrewlinington commented on xyzOrthographicProjection.c
> +
all of these files should be in your corresponding folder renamed to your functionality

2021-11-13 14:16 UTC, andrewlinington commented on xyzOrthographicProjectionTests.h
> +#include "../main.h"
makefile is not updated please update any changes found there

2021-11-16 16:55 UTC, andrewlinington requested changes
![image](https://user-images.githubusercontent.com/57372547/142029699-1352b532-1a5c-4a47-83be-c83d898833d8.png)
 review the naming of some of your functions and consider naming them something specific to your group as i have noticed a few groups use that same naming convention.

2021-11-17 20:44 UTC, andrewlinington approved these changes
Tests still need to be fixed but im merging the actual code

2021-11-17 21:48 UTC, cc0407 approved these changes

2021-11-17 21:48 UTC, merged