Finished code for x shear!
CIS3250-F21/CIS3250-ClassProject pull request #21
Opened 2021-11-13 21:03 UTC by AFraser16

2021-11-13 22:11 UTC, aidkvndfj requested changes
Looks like there are some issues with compiling, I'm getting lots of warnings. Please fix and we'll go from there. If you need help getting the latest changes from master, let us know.

2021-11-13 22:12 UTC, aidkvndfj commented
Please also change the folder name to reflect your role in changing the shape.

2021-11-14 14:46 UTC, AFraser16 commented
I think everything is fixed up now.

2021-11-15 17:54 UTC, cc0407 requested changes
- Please remove the tstFlag if-else block in your tests.h file. 
- The test handler shouldn't run xShear if all of the tests are successful because we're running xShear later on in the program. 
- When I tried to remove the if-else block myself it segfaulted on your first clean test so im not sure if theres something bigger happening there.
- You shouldnt need to create test points because we will provide each group with their own clean slate of test points (we'll provide 5 points) so you can just remove your createTestPoints(); function.

Once you've implemented these just give it a quick once over with `make`, `./main`, `./main -t`, and the valgrind command from the readMe to make sure it runs without any warnings or errors!

2021-11-15 17:54 UTC, cc0407 commented on ShearInX/ShearInX.h
> +int errorFlag;
if theyre only used in test mode, you could probably move them to the ShearInXTests.h

2021-11-16 21:32 UTC, AFraser16 commented
Updated to further match requests

2021-11-16 21:33 UTC, aidkvndfj approved these changes

2021-11-16 21:34 UTC, aidkvndfj approved these changes
Everything looks good to me, and runs good.

2021-11-16 21:42 UTC, cc0407 approved these changes
Looks great! Runs without warning or error, and valgrind isnt complaining

2021-11-16 21:42 UTC, merged