Group1
CIS3250-F21/CIS3250-ClassProject pull request #22
Opened 2021-11-13 22:05 UTC by Jvarkul

2021-11-13 22:14 UTC, aidkvndfj requested changes
![image](https://user-images.githubusercontent.com/36180341/141660504-efe5c871-f849-4d63-80cd-aad62f5b3544.png)
There seems to be some conflicts with what you've requested, and the changes on master. Please resolve these issues and we will do from there. I recommended pulling the changes from master to the branch, and we can go from there. Please let us know if you need assistance.

2021-11-15 17:41 UTC, cc0407 requested changes
Can you please make a test handler in your ReadInputTests.c and .h file that run all 6 of your tests. Once you've implemented that add it to main.c inside of runAllTests().

Also, remove "group1.h" from groupIncludes.h and add your .h files to groupIncludes.h and groupTestIncludes.h

After that just give it a quick once over with `make`, `./main`, `./main -t`, and the valgrind command from the readMe to make sure it runs without any warnings or errors!

2021-11-17 20:32 UTC, andrewlinington requested changes
a few issues need to be resolved but they are mostly small issues when we get to actually merging to master

2021-11-17 20:32 UTC, andrewlinington commented on ReadInput/ReadInputTests.h
> +char test1(char *, char *, char *);
please rename these to be more group-specific like ReadInputTest1

2021-11-17 20:32 UTC, andrewlinington commented on inputTransformation.txt
> +setZTranslation=0
seems the shear groups were forgotten when i sent the sample so they could be added in here

2021-11-17 20:32 UTC, andrewlinington commented on main.c
> +        fprintf(stderr, "Format %s <input file> <transformation file> <output file>", argv[0]);
add newline

2021-11-17 20:32 UTC, andrewlinington commented on zPlaneReflection/zPlaneReflectionTests.h
> +#ifndef Z_PLANE_REFLECTION_TESTS_H
delete this file

2021-11-17 20:32 UTC, andrewlinington commented on main.c
> -
I know it isn't here but you need to include your tests at the bottom if you want to submit them (if not still add them but comment them out so we know you have them

2021-11-18 04:06 UTC, andrewlinington approved these changes
Looks great good to merge. We Will need to fix tests and adjust the rotation values by multiplying by (pi/180)

2021-11-18 04:19 UTC, vdixon531 approved these changes

2021-11-18 04:20 UTC, merged