Group5
CIS3250-F21/CIS3250-ClassProject pull request #25
Opened 2021-11-14 12:54 UTC by bhana6491

Group5 commits

2021-11-14 16:02 UTC, cc0407 requested changes
- CTRL+F through your files and change all instances of "vector" to "point" and "Vector" to "Point", there's a fair amount of them still there.
- If you can, rename your files & folder to "ScalingInZ", to follow the naming conventions of other groups
- Once that's done make it and run `./main` and `./main -t` to make sure there are no issues

2021-11-14 19:07 UTC, cc0407 approved these changes

2021-11-15 18:17 UTC, cc0407 commented
I don't think line 204 inside of your incrementedPoint function will ever evaluate to true. The first point's z-value will be 0 before you scale it and then after you scale it it'll still be 0. The if-statement checks if the z-value isnt 4, and 0 != 4. I might not be looking at it correctly though, please let me know if any clarification is needed!

2021-11-15 18:19 UTC, andrewlinington approved these changes
Please fix the tests in the next Pr

2021-11-15 18:20 UTC, merged