ifndef update and zeroTransformationTest fix
CIS3250-F21/CIS3250-ClassProject pull request #26
Opened 2021-11-14 16:27 UTC by mbahgatTech

Fixed the uninitialized array of points in zeroTransformationTest.
Fixed a loop error that went over 4 vectors no matter the numOfPoints value.
Changed the ifndef define names to SCALINGINX

2021-11-14 17:12 UTC, cc0407 requested changes
- The test functions are still seg-faulting. They're trying to grab points using getPoint() but there are no points in the list. It might be a better idea to manually create test points and check if your scaling function works on them, that way its independent of the amount of points in the global list
- I'd recommend using CTRL+F and changing all instance of "vector" and "Vector" to "point" and "Point". Just so it stays consistent with the naming conventions.
- I had commented out `runScalingInXTests()` inside of main.c a bit ago so the seg-fault wouldn't interfere with other groups code, please uncomment it before testing if you're not already :)

2021-11-14 21:09 UTC, mbahgatTech commented
1. Fixed the seg faults in the first commit. (Tests seg fault fix)
2. Changed a parameter error in the second commit (x Tests)

2021-11-16 06:40 UTC, andrewlinington approved these changes
changes have resolved issues in tests and should be good to merge

2021-11-16 15:23 UTC, cc0407 approved these changes

2021-11-16 15:23 UTC, merged