fixed tests and valgrind issues
CIS3250-F21/CIS3250-ClassProject pull request #40
Opened 2021-11-16 22:18 UTC by zalgayya

2021-11-16 22:39 UTC, cc0407 approved these changes
Awesome! No warnings or errors, and a clean valgrind.

Good to merge in

2021-11-16 22:52 UTC, andrewlinington requested changes
i think there may be a small error where i commented could you review it to ensure this code performs what you expect

2021-11-16 22:52 UTC, andrewlinington commented on GlobalScaling/GlobalScaling.c
> +        negativeScale = 0;
negative scale is always 0 with how this was done

2021-11-16 22:52 UTC, andrewlinington commented on GlobalScaling/GlobalScaling.c
> +        if(negativeScale){
never is run

2021-11-17 20:05 UTC, aidkvndfj approved these changes
Everything looks good and runs well.

2021-11-17 20:36 UTC, merged